name: "Fosstars (OSS rules of play)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: "Open source rules of play"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/oss-rules-of-play-action
        with:
          fosstars-version: oss-rules-of-play
          report-branch: fosstars-oss-rules-of-play-test-report
          token: "${{ secrets.GITHUBTOKEN }}"
